- name: debug
  debug:
     msg: "schema {{ schema }}"

- name: check if schema is loaded
  command: "ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn=schema,cn=config dn"
  register: ldap_schema_list

- name: import additional schemas
  command: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/{{ schema }}.ldif"
  when: schema not in ldap_schema_list.stdout

